### ISSUE TITLE
Release 4.0 roll-out plan / progress

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#1687]
- [x] Upload 4.0 to Google Play, beta channel.
- [x] Promote to Production, 5%
- [x] Sync Play Store Descriptions #1686
- [x] Update Play Store graphics #1127
- [x] Pull new graphics to fastlane dirs
- [ ] Set up graphics on some channels #1127
- [x] Fix #1720 and #1718
- [x] Production 99.999 % (still cancelable)
- [x] Production 100 %
- [x] Submit to Amazon
- [x] Publish to Amazon
- [x] Submit to Samsung
- [x] Publish to Samsung
- [x] Submit to Huawei
- [x] Publish to Huawei
- [x] Submit to F-Droid
- [x] Published in F-Droid

Send announcement to (100% published in all channels)

- [x] mailing lists
- [x] facebook

**Comment by tuomas2** [comment]
- [x] Upload 4.0.600 to Google Play, beta channel.
- [ ] Promote to Production, 10%
- [ ] ... 50%
- [ ] ... 99.99%
- [ ] ... 100 %
- [ ] Publish to Amazon
- [ ] Publish to Samsung
- [ ] Publish to Huawei
- [ ] Publish to F-Droid

**Comment by tuomas2** [comment]
Build 601 now rolling out. Fixed chinese translations.

**Comment by tuomas2** [comment]
Roll-out updated to 15%

**Comment by agrogers** [comment]
If someone random goes to the play store do they get version 4?

**Comment by tuomas2** [comment]
As far as I understand, with 15% probability they do. So I would restrain advertising until we are at 99.999% or 100%.

**Comment by agrogers** [comment]
Got ya.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
First review on Play

> Loving the enhancements recently made, really great thanks! Only thing for others to know, was that after the update to new version (4.0.601 9/9/21), you might think you have lost the app, as both the Icon, and it's position in app List has changed, due to the new name. Thanks again! God bless!

**Comment by tuomas2** [comment]
F-droid builds always take some days, but I have created a tag so new version should pop out there any time now.

**Comment by agrogers** [comment]
Oh, yeah, that is a good point. A change of name and icon is a gotya!
Perhaps we should have only changed one this time and the other on the next
major release.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by tuomas2** [comment]
F-droid build is successfull. Still might take few days to get to f-droid app listing.

Build info: https://f-droid.org/wiki/page/net.bible.android.activity/lastbuild

App web page https://f-droid.org/en/packages/net.bible.android.activity/

**Comment by Dleemuse** [comment]
I really love all the improvements in version 4.0. The YouTube tutorial is very nice. You guys have done such a wonderful job, I know you have put in long hours on the upgrades.

I can't wait until it is released on Amazon so I can use all the new features on my Kindle, & my hubby will be even happier than myself as he has an iPhone so only has AB on his kindle. 

Thank you, thank you, thank you! You have all done a fantastic job, & I really appreciate it! 

Debra

**Comment by agrogers** [comment]
Thanks for your kind words Debra. People are much more likely to contact us with a problem (and sometimes rudely) so it is lovely to hear your encouragement. I'm not sure when the Amazon store will be updated - Tuomas might be able to comment on that. Oh, and please keep using the beta version and send through your thoughts. They are helpful to us.

**Comment by tuomas2** [comment]
>  I'm not sure when the Amazon store will be updated 

Around the same time as 100% Google Play users will get 4.0. Most likely couple of weeks max. I'll see on thursday what is the situation and do decisions based on that. 

@AndBible/developers, please let me know which issues you think should be fixed ASAP. Can also label them with Prio: High.

**Comment by Dleemuse** [comment]
Your welcome Andrew. 
Thank you Tuomas, 

Sent from Yahoo Mail on Android 
 
  On Tue, Sep 14, 2021 at 9:02 AM, Tuomas ***@***.***> wrote:   



I'm not sure when the Amazon store will be updated


Around the same time as 100% Google Play users will get 4.0. Most likely couple of weeks max. I'll see on thursday what is the situation and do decisions based on that.

@AndBible/developers, please let me know which issues you think should be fixed ASAP. Can also label them with Prio: High.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tuomas2** [comment]
Released 4.0.602 to beta channel. Will promote it to Production (15%) tomorrow (and create tag for f-droid) if no new issues arise.

**Comment by tuomas2** [comment]
602 available to prod users 15%. also triggered f-droid.

**Comment by tuomas2** [comment]
Increased rollout percentage to 25%

**Comment by tuomas2** [comment]
Released 4.0.603 with few bug fixes to beta channel and triggered f-droid. Will promote it to Production (25%) during weekend too.

**Comment by tuomas2** [comment]
v4.0.601 seem to be now available for [F-droid users](https://f-droid.org/en/packages/net.bible.android.activity/).

**Comment by tuomas2** [comment]
Released 4.0.604 to beta channel and triggered f-droid. Will promote it to Production (25%) during weekend too.

**Comment by tuomas2** [comment]
Promoted to prod 4.0.604 (25%)

**Comment by tuomas2** [comment]
4.0.605 (with crash fixes) to beta users

**Comment by tuomas2** [comment]
4.0.605 to production 25%

**Comment by tuomas2** [comment]
4.0.605 to production 99.99999 %

**Comment by tuomas2** [comment]
Rollout paused due to #1744.

**Comment by tuomas2** [comment]
Roll-out continued back with 25% (allowing those that got 601-604 to upgrade to 605). #1756 investigation goes on, and (the few) users affected by that are suggested to downgrade according to [instructions given in FAQ](https://github.com/AndBible/and-bible/wiki/FAQ#how-do-i-downgrade-from-40-to-33) until the issue is fixed. 607 will be released to production after a little beta testing first.

**Comment by tuomas2** [comment]
Roll-out 4.0.608 to production 25%, with #1756 fix/workaround. Also tagged f-droid.

**Comment by tuomas2** [comment]
now 99.999%

**Comment by tuomas2** [comment]
Now 100%. Announcement / "press release" #1740 draft in dev team table, will send soon...

**Comment by tuomas2** [comment]
Submitted update (4.0.610) to Samsung store

**Comment by tuomas2** [comment]
Submitted update (4.0.610) to Huawei store

**Comment by tuomas2** [comment]
Amazon also ready to submit now BUT... should get some info to #1766...

**Comment by tuomas2** [comment]
I could of course release this only to Kindle Fire 10+ devices, if in doubt... And leave 3.3 for the rest. Amazon store allows that.

**Comment by tuomas2** [comment]
Submitted 4.0 to these devices in Amazon Store. All devices that have Fire OS 7 according to this page:  https://developer.amazon.com/docs/fire-tablets/ft-identifying-tablet-devices.html

Others will be served with version 3.3.

![Selection_204](https://user-images.githubusercontent.com/5811789/135476557-8c02edfa-1339-4f87-8bb3-1ded0a21d81b.png)

**Comment by agrogers** [comment]
So these devices have a webview that works?

**Comment by tuomas2** [comment]
> So these devices have a webview that works?

@timbze  has said that his Kindle has WebView 84 so I believe so.

**Comment by tuomas2** [comment]
Samsung published! Now everyone go to Samsung Galaxy Store and give 5 star review :-) (I was the first one to give...)

**Comment by Dleemuse** [comment]
> Samsung published! Now everyone go to Samsung Galaxy Store and give 5 star review :-) (I was the first one to give...)

Following orders team captain, lol (don't mind me, hubby spent 20 year in US Army, & you all know that I have delusions of being a part of the AB team, lol), I just went to Samsung Galaxy Store & left review. In all seriousness though now, these new releases are exciting, thanks one & all for your dedication!

**Comment by tuomas2** [comment]
Huawei AppGallery also now has new version -- if you have huawei phone drop review there too :-) 

Now waiting for only Amazon and soon we can close this ticket :-)...

**Comment by dbell154** [comment]
I suspect most regular users had an icon on their home screen. 
> Oh, yeah, that is a good point. A change of name and icon is a gotya! Perhaps we should have only changed one this time and the other on the next major release.

**Comment by tuomas2** [comment]
> I suspect most regular users had an icon on their home screen.
> 
> > Oh, yeah, that is a good point. A change of name and icon is a gotya! Perhaps we should have only changed one this time and the other on the next major release.

But name was changed already in 3.3 and only icon in 4.0. They were not changed at the same time.

**Comment by tuomas2** [comment]
Sent email, shared on facebook. Press release: https://github.com/AndBible/and-bible/wiki/Press-release:-Bible-Study-App-version-4.0-has-been-released

**Comment by tuomas2** [comment]
all done!

**Comment by Dleemuse** [comment]
I am so excited, I just updated AB on my Kindle! My husband thanks you too (I have mentioned in the past  that he could give up his iPhone for an android to get AB, lol), he is happy that he can now get the updated version on his Kindle. 

I cannot thank you guys enough for all the work you have put into this project.

Debra

**Comment by agrogers** [comment]
Thanks Debra. Your generous comments counteract some of the less generous
ones we receive.
