### ISSUE TITLE
Personal notes (My Notes) improvements

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#188]
From user: 
> "Search & Study" His Word, to areas like personal NOTES by adding SORT/SEARCH feature, Export/ Print etc., if possible - 
> (1) to be able to see FootNotes & Refs on a split window alongside Bible (just like a regular hardcopy bible). Also personal NOTES, if possible 
> (2) sort possibility for personal NOTES if there is any Header/Title associated with it. 

From another user:
>  I would like it for the top toolbar bar to be visible in "note taking mode" even if full screen is set, primarily to allow a return-to-text button to be visible. Thanks.

Other ideas:

- [x]  - Ability to render cross referenses to a links
- [x]  - show / edit "my notes" as a window (like other translations) 
- [x]  - rich text editing
- [x]  - tagging notes and filtering them per tag. Option to hide some tags.
- [x]  - Show more of the Note in the Notes List (#690)
- [x]  - #705

**Comment by mattzab** [comment]
+1 rendering cross references to links

**Comment by tuomas2** [comment]
Created #224 about (1)

**Comment by tuomas2** [comment]
From Google Play:

> Is it possible to add a note preview on verses by selecting the pencil in a verse, rather than going to "my notes" and scrolling through all notes made for all books before getting to it. Please check.

**Comment by mjdenham** [comment]
The above user does not seem to realise that re-selecting the verse and then selecting the Note takes you directly to the note.  Hoever, I would also vote for touching the pencil to take you to the note.
Another issue raised in the first mesage is that touching a footnote ref should show the footnote.

**Comment by tuomas2** [comment]
From user via email
>  Format Feature for edits. bold, underline, embed notes or pictures

**Comment by agrogers** [comment]
I second the idea of showing the user Notes as a standard commentary. That would be way cool.

This could also provide the search functionality. If notes were stored as a user commentary then all the search capabilities could flow onto it. Indexing would need to be kept up to date.

**Comment by tuomas2** [comment]
@JJK96 about "my notes" improvements that you mentioned in our dev meeting, I have thought that editing of my notes could be implemented as a popup dialog, or perhaps another activity, and editing could be activated from window menu button. So I don't know if there's too much work to get that done, if you have already implemented viewing my notes in a window.

Another activity might be better idea because it would allow adding more features to the editing functionality. We might want to use some kind of rich text editing component also to the "my notes" editor.

**Comment by JJK96** [comment]
If we can implement rich editing in a window, this could make a flexible highlighting system also easier to implement, I want to explore that route first, before resorting to the easier option.

**Comment by tuomas2** [comment]
Everything implemented in develop

**Comment by alan2675** [comment]
I made this request in the google group but maybe it is more appropriate here:
With the upcoming support for Android apps on Windows 11, more people might find AndBible on a laptop to be a suitable platform for taking notes during a sermon. It would be great to have a note-taking feature built into the app, with searchable notes organized by topic and by date.

**Comment by agrogers** [comment]
Hi Alan. Have you been using the beta version? It will be publicly released very soon as v4. We have some very good note taking functionality in that version. Check out these two videos for more info...
https://www.youtube.com/watch?v=--Hr5LqBfmg&list=PLD-W_Iw-N2MkMiGz7cjGASOYjElr1Q76m

**Comment by alan2675** [comment]
Those features are great but those notes appear to be organized by verse, so each note pertains to a particular verse.  That's great for individual study but not quite what I want for taking notes in a sermon.  What I'm looking for is a note that is not attached to one verse, but to a topic / sermon title, or date.  Each note would potentially link to multiple verses or verse ranges.  I would go back to the note later by title, not by verse.

BTW thanks for pointing out that video. I'm subscribed to the channel but that video doesn't appear there.  Are there others?

**Comment by timbze** [comment]
@alan2675 there were 2 videos in the play list, did you see the second one? This: https://youtu.be/4gLyW3P9Phs

**Comment by timbze** [comment]
@alan2675 A study pad attaches to a label, not to a verse. And you can link verses to it. I think it is very close to what you are asking for

**Comment by agrogers** [comment]
Yes, the second video describes how you can add a note to a label (ie a
sermon in your case) and not to a verse. In fact you can add many notes,
indent them, include your own cross-references in them and more.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by alan2675** [comment]
Thanks, that's getting a lot closer.  I'll have to try it to see if it works for me.  What I'm used to is essentially a word processor with links to scripture references. I keep my verse notes separate from my sermon notes.  So when I'm studying and making notes on the verse, it doesn't interfere with my sermon notes. And my sermon notes are limited to what the speaker says, without incorporating my prior study notes.  The video seems to mingle those two things. But I need to try it to see.  Maybe it just comes down to how I use the features.  

I'm not using the beta, but it appears to be close to being released. When will it be on the play store?

**Comment by timbze** [comment]
Yes the study pad allows you to add notes separate from verses, and to add links for Bible references in the notes.

The release started yesterday for a small percent of users on Play Store, if everything works out well then it will be released to more/everyone in the coming days/weeks

**Comment by alan2675** [comment]
Thanks everyone. I'm very eager to get my hands on this.  I love AndBible and really appreciate your work!

**Comment by alan2675** [comment]
Ok I have the beta and am running it in BlueStacks on my laptop.  So far so good.  I create a study pad, open it and click the + to add text. Inside the text box I click the Bible icon and type a reference. I then long-press the reference, and it offers to open in a new window or in the current window.  If I say current window, the study pad window goes away - not what I want. If I click on new window, it opens a new Bible window. And if I type another reference and long-press and say new Bible window, it opens yet another.  What I want is for it to change the reference in the currently open and synchronized Bible window. Is that possible? or maybe it's a feature request.  

I know I can add the label to a verse in the Bible window to add the verse to the study pad.  But that takes multiple steps and requires moving back and forth between the mouse and the keyboard on my laptop.  Typing as the speaker talks, I will not be able to keep up with the extra motion.  

Anyway, I'm obviously just learning so take it with a grain of salt.  Thanks!

**Comment by alan2675** [comment]
One last comment: I need the ability to export and share a complete study pad (docx / odt / pdf is ok).  Sermon notes need to be shareable.

**Comment by agrogers** [comment]
Hi Alan. Have you tried a single click on your verse reference not a long click? That should open the reference up in a link window as I think you described. The long press option is for special cases.

I am not sure about the syncing though. Perhaps you can send a screenshot of your setup.

Re keyboard navigation and entry, I have never tried it on a keyboard so can't help you there. I suspect there is not too many keyboard shortcuts enabled. But it is a good idea and something we should consider.

**Comment by agrogers** [comment]
Oh, there is no export option yet but it is on our radar. The best option at the moment is to long click and choose Select All and then Copy your selection. You can then paste it wherever you want.

**Comment by tuomas2** [comment]
Please note that you are commenting on closed ticket, so these discussions will be forgotten (I am not reading everything immediately and will surely forget to follow later closed tickets). Please create new discussion issue for discussion and then always create new feature tickets if there is no existing ticket for it (please check first if it does so that we don't get too many duplicates).

**Comment by alan2675** [comment]
Thanks everyone.  I'll check to see if I can find a ticket on the export function and will add one if I don't find it.

agrogers: Thanks, I don't remember where i got the idea for long pressing the reference but the simple tap does what I want.
