### ISSUE TITLE
New bibleview-js leftovers

### ISSUE THREAD

**Issue by tuomas2** [AndBible/and-bible#922]
Known issues (that will be fixed after merge, but before next stable release):

- [ ] Performance in general due to vue.js rendering. Solution: render smaller chunks at time and rest asynchronously without disturbing user. #976
- [x] Performance of bookmarking long verse ranges. Solution: use different routine for those parts that contain whole verses.
- [x] Speak bookmarks are not displayed correctly
- [x] ensureBibleViewVisible() - when writing notes, text input could be hidden
- [x] readFootnotesAndReferences() - list view of these is not implemented (thinking if it is important or not)
- [x] compare translations (list view) function missing
- [x] share / copy function missing #971
- [x] Custom CSS not implemented (@bvahedy note!!!)
- [x] Debug / production mode for vuecli builds automatically in build.gradle
- [x] RTL texts
- [ ] RTL UI #970 
- [x] translation of strings (some js i18n lib needed)
- [x] "Show bookmarks" should be removed or moved under "Bookmarking settings"
- [ ] Jump to offset (for non-bibles) does not work #972

Note:
- bookmark styles like underline and "yellow star" are not supported any more

**Comment by tuomas2** [comment]
- [x] In night mode the text is still not correct when night text color is set to default. (red letters are ok)
- [ ] I think there should be a way to easily bookmark a verse without having to highlight it all manually. 
- [x] IMO, Verse number is not needed at start of commentaries (see pic 1 below)
- [x] I think the bookmark "create**d** in" should have short Bible name, and not Osis ID. This should show bookmark was made in KJV  (see pic 2 below)

**Picture 1:**
![image](https://user-images.githubusercontent.com/35117769/104938180-53af2e00-5974-11eb-8c1c-579f39c5f62b.png)

**Picture 2:**
![Screenshot from 2021-01-18 12-16-40](https://user-images.githubusercontent.com/35117769/104960101-2fb21380-5999-11eb-9132-10f64ce0d9f3.png)

**Comment by timbze** [comment]
- [x] Bug in bookmark labels where assigned label get's unchecked (d8aa6264)

To reproduce, you need more than a screen full of labels. In my case I have 30+ labels.
1. Save a bookmark with the 5th label checkmarked
2. Open the bookmark labels and you see the checkmark on 5th label
3. Scroll down till label is out of view, and then scroll back up again
4. Checkmark on label 5 is no longer checked

**Comment by timbze** [comment]
- [ ] Suggestion: when there's more than 1 note on a verse, show both in the pop-up. For example, Gen 29:1 in KJV shows "h  i" after verse, and then I have to click each letter separately to see the 2 notes.

**Comment by timbze** [comment]
- [ ] when commentary does not have content for a verse it says "Error occurred" in header style. And then also "not found in document" and "report a bug". When the commentary does not have the content for the verse it should not say error, and I don't  think it should say report a bug, either.  -> #973

**Comment by timbze** [comment]
- [x] scroll to wrong verse issue in ad5117c8
- [x] new issue, now linked commentary in second window loads nothing at all when opening first time in 335ca101

https://support.andbible.org/scp/tickets.php?id=325
https://support.andbible.org/scp/tickets.php?id=331

**Comment by timbze** [comment]
- [x] switching to full screen makes text scroll up too far (about double of what it should). Switching from full screen to non-full screen does the same in reverse, scrolls too far down.
- [x] opening footnote in fullscreen opens modal and brings out of full screen. I think staying in full screen would be better.

**Comment by timbze** [comment]
- [ ] Hebrews 13:25 footer issue. The number 25 should be at the line above it. (TB 2021-02-19 still have the issue in 84e588ec)

![image](https://user-images.githubusercontent.com/35117769/106155452-506f2b80-6146-11eb-88f9-156ff3780dab.png)

**Comment by tuomas2** [comment]
- [x] A couple more points, due to the merge of mynotes and bookmarks all texts with a note now are highlighted blue, it would be better to make it a little less obtrusive, just a note icon would work, or if it's tricky to determine if an unlabeled bookmark has a note, just a star or something. Another thing, I miss being able to select a verse and share including reference. Maybe we could put that functionality back in the menu and use all verses that are partially selected and share them fully. (@JJK96) 
 -> unlabled style can be configured now (or hidden if desired)

**Comment by tuomas2** [comment]
- [ ] The journal button for exit edit mode (pencil with line through), might be nice to simply have a "save" icon. I'm thinking of the floppy disk icon that is used almost everywhere for save
- [ ] Another idea, I think it might be nice if the edit text expanded to about double the height when more text rows get added.
Also, don't know if possible, but when I have 8 lines of text and I tap in the middle or end the edit always opens with cursor at the start of first word. Would be nice if the cursor was more less where I had tapped

**Comment by timbze** [comment]
- [ ] Bible text selection context menu
1. Remove "Select all" menu option" (see developer.android link below on how it can be done)
2. Possibly override "Copy" and "Share" to show a popup (or bottom sheet) with options like 1. "Copy selection", 2. "Copy full verse"

These changes should most likely be only for Bible type documents. E.g. Select all should probably be available for commentary or MyNotes

https://stackoverflow.com/a/52765047
https://developer.android.com/reference/android/widget/TextView#setCustomSelectionActionModeCallback(android.view.ActionMode.Callback)

 ->  unfortunately this applies only to TextView, not WebView

**Comment by timbze** [comment]
- [x] Study pad does not refresh properly when bookmark is added https://support.andbible.org/scp/tickets.php?id=356

**Comment by timbze** [comment]
- [x] Large text font causes bookmark modal buttons to get bigger than there is room, see pic:
![Screenshot_20210219-095825](https://user-images.githubusercontent.com/35117769/108529055-b197a400-7299-11eb-9d94-5125fb25b742.png)

**Comment by timbze** [comment]
- [ ] Possibly consider making an optional full-screen note window. If user wants to write a long note they would definitely like that. It could be something like Gmails "Popout" button on compose window

**Comment by timbze** [comment]
- [x] I think the note text should have the size of Bible text. After fixing the buttons growing too large with large font size, the note text font size now also stays small. 

![Screenshot_20210227-052541.png](https://user-images.githubusercontent.com/35117769/109385978-29c72080-78bd-11eb-906b-a879ba292624.png)

**Comment by timbze** [comment]
- [ ] Make it possible to select consistent colors from 1 label to the next one. Now there is only color picker and so it's impossible to have the same custom color between different labels

- one way would be to have to color code that could be copied
- or have a number of custom colors that can be saved
- or see some of last colors used

**Comment by timbze** [comment]
- [ ] Study pad does not update when switching workspace
1. Open study pad for "label 1" in workspace 1
2. Go to workspace 2 and add "label 1" to some verse bookmark
3. Go back to workspace 1, study pad does not update to show the bookmark that was just added, but it should #977

**Comment by tuomas2** [comment]
I'm thinking that maybe it's time to start writing separate bug tickets instead of collecting stuff here.

**Comment by tuomas2** [comment]
I have made separate issues of remaining (IMO) important issues. @timbze you could go through your remaining ideas and make issues of them if you feel them still important. I'll close this now.
